---
  name: build OpenRV for MacOS
  
  on:
    push:
      branches: ["ci/build-macos"]
  
  jobs:
    build:
      runs-on: macos-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Set Xcode version
          run: sudo xcode-select -s '/Applications/Xcode_14.3.app/Contents/Developer'
        - name: Check Xcode version
          run: xcodebuild -version

        - name: ensure brew
          run: |
            which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew update
        - name: install brew dependencies
          run: |
            brew install cmake ninja readline sqlite3 xz zlib tcl-tk autoconf automake libtool python yasm clang-format black meson nasm pkg-config glew

        - name: ensure qt
          run: |
            pip install aqtinstall
            aqt list-qt mac desktop
            python -m aqt install 5.15.2 mac desktop -O ../qt
            ls -la ../qt
            ls -la ../qt/5.15.2
            echo "QT_HOME=/Users/runner/work/OpenRV/qt/5.15.2/" >> $GITHUB_ENV

        - name: pip dependencies
          run: |
            pip install -r requirements.txt

        # - name: source rvcmds
        #   run: |
        #     ls -la .
        #     chmod +x ./rvcmds.sh
        #     source ./rvcmds.sh
        # - name: source bashrc
        #   run: |
        #     ls -la $HOME
        #     cat $HOME/.bashrc
        - name: setup
          run: |
            source ./rvcmds.sh
            source $HOME/.bashrc
            rvmk

