---
  name: build OpenRV for MacOS
  
  on:
    push:
      branches: ["ci/build-macos"]
  
  jobs:
    build:
      runs-on: macos-latest
      steps:
      - name: Set Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.app/Contents/Developer'
      - name: Check Xcode version
        run: xcodebuild -version
      - name: checkout
        uses: actions/checkout@v4
  
      - name: source rvcmds
        run: |
          source ./rvcmds.sh
