---
  name: build OpenRV for MacOS
  
  on:
    push:
      branches: ["ci/build-macos"]
  
  jobs:
    build:
      runs-on: macos-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Set Xcode version
          run: sudo xcode-select -s '/Applications/Xcode_14.3.app/Contents/Developer'
        - name: Check Xcode version
          run: xcodebuild -version

        - name: ensure brew
          run: |
            which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew update
        - name: install brew dependencies
          run: |
            brew install cmake ninja readline sqlite3 xz zlib tcl-tk autoconf automake libtool python yasm clang-format black meson nasm pkg-config glew

        - name: ensure qt
          run: |
            pip install aqtinstall
            python -m aqt install 5.15 mac desktop -O /opt/ManualQT/5.15/
            export QT_HOME=/opt/ManualQT/5.15/

        - name: source rvcmds
          run: |
            source ./rvcmds.sh
